@extends('liteback.layout')

@section('title', 'Liteback - Multi-Tier Affiliate Management')
@section('page_title', 'Multi-Tier Affiliate & Referral Engine')

@section('content')
<div class="container-fluid">
    @if(session('success'))
        <div class="alert alert-success alert-dismissible fade show">
            <i class="fas fa-check-circle mr-2"></i> {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
    @endif

    @if(isset($errors) && $errors->any())
        <div class="alert alert-danger alert-dismissible fade show">
            <i class="fas fa-exclamation-triangle mr-2"></i> {{ $errors->first() }}
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
    @endif

    <!-- Metric Stat Widgets -->
    <div class="row">
        <div class="col-lg-3 col-6">
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>${{ number_format($totalPaidOut, 2) }}</h3>
                    <p>Total Paid Affiliate Earnings</p>
                </div>
                <div class="icon">
                    <i class="fas fa-hand-holding-usd"></i>
                </div>
                <span class="small-box-footer">Claimed to Player Cash</span>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>${{ number_format($totalUnclaimed, 2) }}</h3>
                    <p>Unclaimed Player Balances</p>
                </div>
                <div class="icon">
                    <i class="fas fa-wallet"></i>
                </div>
                <span class="small-box-footer">Awaiting 1-Click Claim</span>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ number_format($totalCommissionsCount) }}</h3>
                    <p>Commission Events Recorded</p>
                </div>
                <div class="icon">
                    <i class="fas fa-receipt"></i>
                </div>
                <span class="small-box-footer">Across All Games & Verticals</span>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-primary">
                <div class="inner">
                    <h3>${{ number_format($totalVolume, 2) }}</h3>
                    <p>Downline Wager Volume</p>
                </div>
                <div class="icon">
                    <i class="fas fa-chart-line"></i>
                </div>
                <span class="small-box-footer">Generated by Referral Network</span>
            </div>
        </div>
    </div>

    <!-- Tier Rates Configuration -->
    <div class="card card-outline card-secondary mb-4">
        <div class="card-header">
            <h3 class="card-title font-weight-bold"><i class="fas fa-sliders-h mr-2"></i> 3-Tier Cascade Commission Rates</h3>
        </div>
        <div class="card-body">
            <form action="{{ route('liteback.affiliates.settings') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label><i class="fas fa-user-friends text-warning mr-1"></i> Tier 1 (Direct Referrals) % Rate</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" max="10" name="affiliate_tier1_rate" class="form-control font-weight-bold" value="{{ $rates['tier1'] }}">
                                <div class="input-group-append"><span class="input-group-text font-weight-bold">%</span></div>
                            </div>
                            <small class="text-muted">Default: 0.50% of downline wager</small>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label><i class="fas fa-network-wired text-info mr-1"></i> Tier 2 (Sub-Referrals) % Rate</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" max="10" name="affiliate_tier2_rate" class="form-control font-weight-bold" value="{{ $rates['tier2'] }}">
                                <div class="input-group-append"><span class="input-group-text font-weight-bold">%</span></div>
                            </div>
                            <small class="text-muted">Default: 0.30% of sub-downline wager</small>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label><i class="fas fa-project-diagram text-purple mr-1"></i> Tier 3 (Grand-Sub) % Rate</label>
                            <div class="input-group">
                                <input type="number" step="0.01" min="0" max="10" name="affiliate_tier3_rate" class="form-control font-weight-bold" value="{{ $rates['tier3'] }}">
                                <div class="input-group-append"><span class="input-group-text font-weight-bold">%</span></div>
                            </div>
                            <small class="text-muted">Default: 0.20% of 3rd generation wager</small>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary font-weight-bold"><i class="fas fa-save mr-1"></i> Save Global Tier Rates</button>
            </form>
        </div>
    </div>

    <!-- Top Affiliates Table -->
    <div class="card card-outline card-primary mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="card-title font-weight-bold"><i class="fas fa-trophy text-warning mr-2"></i> Top Affiliates & Promoters</h3>
            <div class="card-tools">
                <form method="GET" action="{{ route('liteback.affiliates.index') }}" class="form-inline">
                    <div class="input-group input-group-sm" style="width: 250px;">
                        <input type="text" name="search" class="form-control float-right" placeholder="Search affiliate or code..." value="{{ $search }}">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>User</th>
                        <th>Invite Code</th>
                        <th>Direct Referrals</th>
                        <th>Unclaimed Balance</th>
                        <th>Total Lifetime Paid</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($topAffiliates as $aff)
                    <tr>
                        <td>{{ $aff->id }}</td>
                        <td>
                            <strong>{{ $aff->username }}</strong>
                            <div class="text-muted small">{{ $aff->email ?? 'No email' }}</div>
                        </td>
                        <td><span class="badge badge-secondary font-monospace">{{ $aff->invite_code ?: 'N/A' }}</span></td>
                        <td><span class="badge badge-info">{{ $aff->count_invite ?? 0 }} Users</span></td>
                        <td>
                            <strong class="text-warning">${{ number_format($aff->unclaimed_commissions, 2) }}</strong>
                        </td>
                        <td>
                            <strong class="text-success">${{ number_format($aff->total_affiliate_earnings, 2) }}</strong>
                        </td>
                        <td>
                            <a href="{{ route('liteback.users.detail', $aff->id) }}" class="btn btn-xs btn-outline-primary"><i class="fas fa-user-edit mr-1"></i> View Profile</a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="text-center py-4 text-muted">No affiliate accounts matching search.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if($topAffiliates->hasPages())
        <div class="card-footer clearfix">
            {{ $topAffiliates->appends(['search' => $search])->links() }}
        </div>
        @endif
    </div>

    <!-- Recent Commission Ledger -->
    <div class="card card-outline card-info">
        <div class="card-header">
            <h3 class="card-title font-weight-bold"><i class="fas fa-history mr-2"></i> Global Commission Activity Ledger</h3>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-hover table-sm text-nowrap">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Time</th>
                        <th>Affiliate Earned</th>
                        <th>Referred Player</th>
                        <th>Tier</th>
                        <th>Vertical</th>
                        <th>Wager</th>
                        <th>Commission</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($recentCommissions as $item)
                    <tr>
                        <td>#{{ $item->id }}</td>
                        <td>{{ $item->created_at ? $item->created_at->format('Y-m-d H:i') : '-' }}</td>
                        <td><strong>{{ $item->affiliate->username ?? 'ID: ' . $item->affiliate_id }}</strong></td>
                        <td>{{ $item->referredUser->username ?? 'ID: ' . $item->referred_user_id }}</td>
                        <td>
                            @if($item->tier == 1)
                                <span class="badge badge-warning">Tier 1</span>
                            @elseif($item->tier == 2)
                                <span class="badge badge-info">Tier 2</span>
                            @else
                                <span class="badge badge-secondary">Tier 3</span>
                            @endif
                        </td>
                        <td><span class="badge badge-light border">{{ strtoupper($item->game_type) }}</span></td>
                        <td>${{ number_format($item->wager_amount, 2) }}</td>
                        <td><strong class="text-success">+${{ number_format($item->commission_amount, 4) }}</strong></td>
                        <td>
                            @if($item->status === 'claimed')
                                <span class="badge badge-success">Claimed</span>
                            @else
                                <span class="badge badge-warning">Pending</span>
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="9" class="text-center py-4 text-muted">No commission events recorded yet.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if($recentCommissions->hasPages())
        <div class="card-footer clearfix">
            {{ $recentCommissions->links() }}
        </div>
        @endif
    </div>
</div>
@endsection
